# Generated by Django 4.2.17 on 2024-12-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistID', models.AutoField(primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('NoOfMembers', models.IntegerField()),
                ('YearStarted', models.IntegerField()),
                ('YearEnded', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('LabelID', models.AutoField(primary_key=True, serialize=False)),
                ('LabelName', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('SongID', models.AutoField(primary_key=True, serialize=False)),
                ('SongName', models.CharField(max_length=100)),
                ('SongLength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('VenueID', models.AutoField(primary_key=True, serialize=False)),
                ('VenueName', models.CharField(max_length=255)),
                ('VenueCapacity', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('ConcertID', models.AutoField(primary_key=True, serialize=False)),
                ('ConcertName', models.CharField(max_length=200)),
                ('ConcertDate', models.DateField()),
                ('VenueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumID', models.AutoField(primary_key=True, serialize=False)),
                ('AlbumName', models.CharField(max_length=50)),
                ('ReleaseDate', models.DateField()),
                ('LabelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.label')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertSongArtist',
            fields=[
                ('ConcertSongArtistID', models.AutoField(primary_key=True, serialize=False)),
                ('ArtistID', models.ForeignKey(db_column='ArtistID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.artist')),
                ('ConcertID', models.ForeignKey(db_column='ConcertID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.concert')),
                ('SongID', models.ForeignKey(db_column='SongID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.song')),
            ],
            options={
                'unique_together': {('SongID', 'ConcertID', 'ArtistID')},
            },
        ),
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
                ('ArtistSongID', models.AutoField(primary_key=True, serialize=False)),
                ('ArtistID', models.ForeignKey(db_column='ArtistID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.artist')),
                ('SongID', models.ForeignKey(db_column='SongID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.song')),
            ],
            options={
                'unique_together': {('SongID', 'ArtistID')},
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('AlbumSongID', models.AutoField(primary_key=True, serialize=False)),
                ('AlbumID', models.ForeignKey(db_column='AlbumID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.album')),
                ('SongID', models.ForeignKey(db_column='SongID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.song')),
            ],
            options={
                'unique_together': {('SongID', 'AlbumID')},
            },
        ),
    ]
