# Generated by Django 4.2.17 on 2024-12-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='VenueID',
            field=models.ForeignKey(db_column='VenueID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.venue'),
        ),
    ]
