# Generated by Django 4.2.17 on 2024-12-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0002_alter_concert_venueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='LabelID',
            field=models.ForeignKey(db_column='LabelID', on_delete=django.db.models.deletion.CASCADE, to='artist_app.label'),
        ),
    ]
